# spring:
#   application:
#     name: myapp
# logging:
#   level:
#     '[com.sk.skala.myapp.controller]' : DEBUG
#     '[com.sk.skala.myapp.service]' : DEBUG
# server:
# port: 8080
# spring:
# datasource:
# url: jdbc:mysql://localhost:3306/stockdb
# username: stockuser
# password: stockpw
# logging:
# level:
# org.springframework: INFO
# stock:
# api:
# base-url: https://api.stock.com

spring:
  application:
    name: myapp
  profiles:
    active: local

logging:
  level:
    '[com.sk.skala.myapp.controller]': DEBUG
    '[com.sk.skala.myapp.service]': DEBUG
